import type { Hotel, Destination, BlogPost, Offer, Review } from "./types";

export const DESTINATIONS: Destination[] = [
  {
    id: "grg",
    city: "Gurgaon",
    state: "Haryana",
    slug: "gurgaon",
    description: "India's corporate capital — with 15+ LimeTree properties near Cyber City, IFFCO Chowk, Golf Course Road, and top hospitals.",
    image: "https://assets.simplotel.com/simplotel/image/upload/w_5000,h_3333/x_234,y_0,w_4532,h_3333,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09899_ozpuez",
    propertyCount: 15,
    startingPrice: 1499,
    highlights: ["Cyber City", "IFFCO Chowk", "Golf Course Road", "Near Medanta & Artemis"],
    popularFor: ["Corporate Stays", "Long Stay", "Medical Tourism"],
  },
  {
    id: "del",
    city: "Delhi",
    state: "Delhi",
    slug: "delhi",
    description: "Stay in South Delhi's premier residential zones — Greater Kailash and Kailash Colony — close to metro and business hubs.",
    image: "https://assets.simplotel.com/simplotel/image/upload/x_195,y_0,w_1260,h_927,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-boutique-bed-breakfast-|-nehru-place-metro-1753349469/Hotels-in-Delhi-Lime-Stay-Bedroom_sktjlo",
    propertyCount: 2,
    startingPrice: 1799,
    highlights: ["Greater Kailash-2", "Kailash Colony", "Metro Connectivity"],
    popularFor: ["Business Travel", "Leisure", "Short Stays"],
  },
  {
    id: "grnoida",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    slug: "greater-noida",
    description: "Modern infrastructure meets affordability. Stay near India Expo Mart, knowledge park, and Pari Chowk.",
    image: "https://assets.simplotel.com/simplotel/image/upload/x_194,y_0,w_3852,h_2832,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-and-banquet-greater-noida/DSC00679_nf9ilw",
    propertyCount: 4,
    startingPrice: 1299,
    highlights: ["India Expo Mart", "Pari Chowk", "Knowledge Park"],
    popularFor: ["Exhibition Stays", "Business Travel", "Budget Stays"],
  },
  {
    id: "noi",
    city: "Noida",
    state: "Uttar Pradesh",
    slug: "noida",
    description: "Tech-forward Noida stays — comfortable, well-connected, and perfect for IT professionals and business travelers.",
    image: "https://assets.simplotel.com/simplotel/image/upload/w_5000,h_3335/x_232,y_0,w_4536,h_3335,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-one-bhk-serviced-apartment---noida-sector-50-metro/5_ih0fjv",
    propertyCount: 1,
    startingPrice: 1599,
    highlights: ["Sector 50", "Sector 72", "Metro Connectivity"],
    popularFor: ["IT Professionals", "Corporate Stays", "Family Trips"],
  },
  {
    id: "jai",
    city: "Jaipur",
    state: "Rajasthan",
    slug: "jaipur",
    description: "The Pink City's charm with LimeTree comfort. Hotel & Banquet venue for weddings, events, and leisure stays.",
    image: "https://assets.simplotel.com/simplotel/image/upload/x_0,y_11,w_1448,h_1064,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-banquet-jaipur/hotel-lobby",
    propertyCount: 1,
    startingPrice: 1999,
    highlights: ["City Centre", "Heritage Zone", "Banquet Hall"],
    popularFor: ["Heritage Tourism", "Weddings", "Leisure"],
  },
  {
    id: "vrd",
    city: "Vrindavan",
    state: "Uttar Pradesh",
    slug: "vrindavan",
    description: "Spiritual stays in the holy city — comfortable and well-located for pilgrims and leisure travelers.",
    image: "https://assets.simplotel.com/simplotel/image/upload/x_196,y_0,w_3808,h_2800,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-banquet-vrindavan/Vrindavan-59_564e1a7a",
    propertyCount: 1,
    startingPrice: 1299,
    highlights: ["Pilgrimage Route", "Banquet Hall", "Peaceful Setting"],
    popularFor: ["Pilgrimage", "Spiritual Stays", "Weddings"],
  },
  {
    id: "goa",
    city: "Goa",
    state: "Goa",
    slug: "goa",
    description: "4BHK luxury villa with a private pool — the ultimate escape on India's most beloved coastline.",
    image: "https://assets.simplotel.com/simplotel/image/upload/x_67,y_0,w_1306,h_960,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-villa-with-private-pool-|-luxury-stay-in-goa/Pool2_7939cbbc",
    propertyCount: 1,
    startingPrice: 12000,
    highlights: ["Private Pool", "4BHK Villa", "Beachside"],
    popularFor: ["Family Vacations", "Group Getaways", "Luxury Stays"],
  },
];

export const HOTELS: Hotel[] = [
  {
    id: "lt-grg-iffco",
    slug: "lime-tree-hotel-iffco-chowk",
    name: "Lime Tree Hotel, IFFCO Chowk",
    tagline: "Prime Gurgaon Address, Unbeatable Value",
    description:
      "Positioned at the heart of Gurgaon's most connected junction, Lime Tree IFFCO Chowk is the go-to address for business and leisure travelers. Minutes from Cyber Hub, DLF Cyber City, and major corporate offices, this property combines smart design with genuine warmth.",
    propertyType: "hotel",
    location: {
      city: "Gurgaon",
      state: "Haryana",
      address: "Near IFFCO Chowk Metro Station, Sector 29, Gurugram",
      area: "IFFCO Chowk",
      pincode: "122001",
      nearbyAttractions: ["IFFCO Chowk Metro (2 min walk)", "Cyber Hub (10 min)", "DLF Cyber City (12 min)", "MG Road (5 min)"],
    },
    images: [
      "https://assets.simplotel.com/simplotel/image/upload/w_5000,h_3333/x_234,y_0,w_4532,h_3333,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09899_ozpuez",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09854_ihjj3s",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09827_rwzqjb",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-service-apartment-private-limited/BA_132-02_0236d9e9",
    ],
    heroImage: "https://assets.simplotel.com/simplotel/image/upload/w_5000,h_3333/x_234,y_0,w_4532,h_3333,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09899_ozpuez",
    rating: 4.3,
    reviewCount: 1247,
    starCategory: 3,
    pricePerNight: 1999,
    originalPrice: 2800,
    rooms: [
      {
        id: "lt-grg-iffco-std",
        type: "standard",
        name: "Standard Room",
        description: "Compact, thoughtfully designed room with all essentials for a comfortable business stay.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09854_ihjj3s"],
        size: 22,
        maxOccupancy: 2,
        bedType: "Double",
        pricePerNight: 1999,
        originalPrice: 2800,
        amenities: ["Free WiFi", "AC", "TV", "Geyser", "Work Desk"],
        available: true,
        cancellationPolicy: "free",
        breakfastIncluded: true,
      },
      {
        id: "lt-grg-iffco-dlx",
        type: "deluxe",
        name: "Deluxe Room",
        description: "Spacious room with premium furnishings, extra amenities, and a quieter floor location.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-on-golf-course-extension-road-gurgaon/Lime_Tree_Hotel_Golf_Course_Extension_Road_Gurgaon-_Room_khtpwz"],
        size: 28,
        maxOccupancy: 2,
        bedType: "Queen",
        pricePerNight: 2499,
        originalPrice: 3500,
        amenities: ["Free WiFi", "AC", "Smart TV", "Minibar", "Work Desk", "Safe"],
        available: true,
        cancellationPolicy: "free",
        breakfastIncluded: true,
      },
    ],
    amenities: ["Free WiFi", "Complimentary Breakfast", "24x7 Front Desk", "Parking", "Power Backup", "CCTV Security", "Laundry", "Room Service", "Airport Shuttle"],
    highlights: ["2 min from IFFCO Metro", "Cyber Hub 10 min", "Breakfast Included", "24x7 Support"],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      cancellation: "Free cancellation until 24 hours before check-in",
      pets: false,
      smoking: false,
      children: true,
    },
    tags: ["featured", "business", "metro-access"],
    featured: true,
  },
  {
    id: "lt-grg-millennium",
    slug: "lime-tree-hotel-millennium-city-centre",
    name: "Lime Tree Hotel & Banquet, Millennium City Centre",
    tagline: "Where Business Meets Celebration",
    description:
      "A full-service hotel with banquet facilities near Millennium City Centre Metro. Perfect for corporate events, conferences, weddings, and business stays in one of Gurgaon's most vibrant locations.",
    propertyType: "hotel",
    location: {
      city: "Gurgaon",
      state: "Haryana",
      address: "Near Millennium City Centre Metro, Sector 38, Gurugram",
      area: "Sector 38",
      pincode: "122003",
      nearbyAttractions: ["Millennium City Centre Metro", "Kingdom of Dreams (5 min)", "Ambience Mall (8 min)", "NH-48 (3 min)"],
    },
    images: [
      "https://assets.simplotel.com/simplotel/image/upload/x_0,y_443,w_4200,h_1914,r_0,c_crop/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-and-banquet-hall-near-huda-metro-gurgaon/side_view_of_the_king_size_bed,_the_living_area_and_a_television_in_the_suite_at_Lime_Tree_Hotels_and_Banquet_Hall_Near_Huda_Metro,_Gurgaon",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-and-banquet-hall-near-huda-metro-gurgaon/Banquet_fxsxcz",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-and-banquet-hall-near-huda-metro-gurgaon/Lime_Tree_Hotel_Huda_City_Center_Gurgaon_10_xj2mge",
    ],
    heroImage: "https://assets.simplotel.com/simplotel/image/upload/x_0,y_443,w_4200,h_1914,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-and-banquet-hall-near-huda-metro-gurgaon/side_view_of_the_king_size_bed,_the_living_area_and_a_television_in_the_suite_at_Lime_Tree_Hotels_and_Banquet_Hall_Near_Huda_Metro,_Gurgaon",
    rating: 4.4,
    reviewCount: 892,
    starCategory: 3,
    pricePerNight: 2199,
    originalPrice: 3000,
    rooms: [
      {
        id: "lt-grg-mill-std",
        type: "standard",
        name: "Standard Room",
        description: "Well-appointed room with modern amenities and comfortable bedding.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09854_ihjj3s"],
        size: 24,
        maxOccupancy: 2,
        bedType: "Double",
        pricePerNight: 2199,
        originalPrice: 3000,
        amenities: ["Free WiFi", "AC", "TV", "Work Desk"],
        available: true,
        cancellationPolicy: "free",
        breakfastIncluded: true,
      },
    ],
    amenities: ["Free WiFi", "Banquet Hall", "Complimentary Breakfast", "Parking", "Power Backup", "AC Conference Room", "Catering", "24x7 Front Desk"],
    highlights: ["Metro Access", "Banquet for 200+", "Conference Facilities", "Wedding Venue"],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      cancellation: "Free cancellation until 24 hours before check-in",
      pets: false,
      smoking: false,
      children: true,
    },
    tags: ["featured", "banquet", "events", "metro-access"],
    featured: true,
  },
  {
    id: "lt-grg-32ave",
    slug: "lime-tree-hotel-32nd-avenue",
    name: "Lime Tree Hotel Near 32nd Avenue",
    tagline: "Leisure & Dining at Your Doorstep",
    description:
      "Ideally situated near Gurgaon's most popular leisure destination, 32nd Avenue. Enjoy convenient access to restaurants, entertainment, and shopping while staying in a well-designed boutique hotel.",
    propertyType: "hotel",
    location: {
      city: "Gurgaon",
      state: "Haryana",
      address: "Near 32nd Avenue, Sector 15 Part 2, Gurugram",
      area: "Sector 15",
      pincode: "122001",
      nearbyAttractions: ["32nd Avenue (2 min)", "MG Road Metro (8 min)", "Ambience Mall (15 min)", "Rapid Metro (10 min)"],
    },
    images: [
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-near-32nd-avenue-sector-15-gurgaon/Lime_Tree_Hotels_32nd_Avenue_91_bouivm",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-near-32nd-avenue-sector-15-gurgaon/Lime_Tree_Hotels_32nd_Avenue_15_vhj1yx",
    ],
    heroImage: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-near-32nd-avenue-sector-15-gurgaon/Lime_Tree_Hotels_32nd_Avenue_91_bouivm",
    rating: 4.2,
    reviewCount: 634,
    starCategory: 3,
    pricePerNight: 1799,
    originalPrice: 2500,
    rooms: [
      {
        id: "lt-grg-32ave-std",
        type: "standard",
        name: "Standard Room",
        description: "Comfortable room with modern furnishings and all essential amenities.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09854_ihjj3s"],
        size: 20,
        maxOccupancy: 2,
        bedType: "Double",
        pricePerNight: 1799,
        originalPrice: 2500,
        amenities: ["Free WiFi", "AC", "TV", "Geyser"],
        available: true,
        cancellationPolicy: "free",
        breakfastIncluded: true,
      },
    ],
    amenities: ["Free WiFi", "Complimentary Breakfast", "Parking", "Power Backup", "24x7 Front Desk", "Room Service"],
    highlights: ["Steps from 32nd Avenue", "F&B Hub Nearby", "Metro Accessible", "Breakfast Included"],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      cancellation: "Free cancellation until 24 hours before check-in",
      pets: false,
      smoking: false,
      children: true,
    },
    tags: ["business", "leisure"],
    featured: false,
  },
  {
    id: "lt-grg-gcr",
    slug: "lime-tree-hotel-golf-course-extension",
    name: "Lime Tree Hotel, Golf Course Extension Road",
    tagline: "Corporate Comfort on Gurgaon's Prestige Corridor",
    description:
      "On one of Gurgaon's most prestigious corridors, this property caters to corporate professionals with premium amenities, fast WiFi, and seamless access to major tech parks and corporate offices.",
    propertyType: "hotel",
    location: {
      city: "Gurgaon",
      state: "Haryana",
      address: "Golf Course Extension Road, Sector 65, Gurugram",
      area: "Golf Course Extension",
      pincode: "122101",
      nearbyAttractions: ["Golf Course Ext Road", "Sohna Road (5 min)", "Sector 55-56 Metro (7 min)", "Southern Peripheral Road"],
    },
    images: [
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-on-golf-course-extension-road-gurgaon/Lime_Tree_Hotel_Golf_Course_Extension_Road_Gurgaon-_Facade_d4rspw",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-on-golf-course-extension-road-gurgaon/Lime_Tree_Hotel_Golf_Course_Extension_Road_Gurgaon-_Room_khtpwz",
    ],
    heroImage: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-on-golf-course-extension-road-gurgaon/Lime_Tree_Hotel_Golf_Course_Extension_Road_Gurgaon-_Facade_d4rspw",
    rating: 4.5,
    reviewCount: 521,
    starCategory: 4,
    pricePerNight: 2499,
    originalPrice: 3500,
    rooms: [
      {
        id: "lt-grg-gcr-dlx",
        type: "deluxe",
        name: "Deluxe Room",
        description: "Spacious room with premium furnishings, ideal for extended business stays.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09854_ihjj3s"],
        size: 30,
        maxOccupancy: 2,
        bedType: "King",
        pricePerNight: 2499,
        originalPrice: 3500,
        amenities: ["Free WiFi", "AC", "Smart TV", "Minibar", "Work Desk", "Safe"],
        available: true,
        cancellationPolicy: "free",
        breakfastIncluded: true,
      },
    ],
    amenities: ["Free WiFi", "Complimentary Breakfast", "Business Center", "Parking", "Power Backup", "Gym", "24x7 Front Desk", "Airport Shuttle"],
    highlights: ["Premium Corridor", "Corporate Rates Available", "Business Center", "Gym Access"],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      cancellation: "Free cancellation until 24 hours before check-in",
      pets: false,
      smoking: false,
      children: true,
    },
    tags: ["featured", "business", "premium"],
    featured: true,
  },
  {
    id: "lt-grg-medanta",
    slug: "lime-tree-hotel-near-medanta",
    name: "Lime Tree Hotel Near Medanta–The Medicity",
    tagline: "Comfort & Care, Steps from Medanta",
    description:
      "Specifically designed for patients, attendants, and medical travelers visiting Medanta–The Medicity. Wheelchair-accessible rooms, ground-floor options, pharmacy assistance, and 24x7 support make this the most thoughtful stay near Gurgaon's premier hospital.",
    propertyType: "hotel",
    location: {
      city: "Gurgaon",
      state: "Haryana",
      address: "Sector 38, Near Medanta Hospital, Gurugram",
      area: "Sector 38",
      pincode: "122001",
      nearbyAttractions: ["Medanta–The Medicity (5 min walk)", "AIIMS Jhajjar (20 min)", "Artemis Hospital (10 min)", "IFFCO Chowk Metro (12 min)"],
    },
    images: [
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-service-apartment-private-limited/LT-Sector_38-115_4e3d5eaa",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-service-apartment-private-limited/BA_132-02_0236d9e9",
    ],
    heroImage: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-service-apartment-private-limited/LT-Sector_38-115_4e3d5eaa",
    rating: 4.6,
    reviewCount: 1834,
    starCategory: 3,
    pricePerNight: 1699,
    originalPrice: 2400,
    rooms: [
      {
        id: "lt-grg-med-std",
        type: "standard",
        name: "Standard Room",
        description: "Thoughtfully designed for medical travelers — quiet, clean, with wheelchair access.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09854_ihjj3s"],
        size: 22,
        maxOccupancy: 2,
        bedType: "Double",
        pricePerNight: 1699,
        originalPrice: 2400,
        amenities: ["Free WiFi", "AC", "TV", "Wheelchair Access", "Geyser"],
        available: true,
        cancellationPolicy: "free",
        breakfastIncluded: true,
      },
    ],
    amenities: ["Free WiFi", "Complimentary Breakfast", "Wheelchair Access", "Pharmacy Assistance", "Pick-up & Drop", "24x7 Front Desk", "Parking", "Power Backup"],
    highlights: ["5 min from Medanta", "Wheelchair Accessible", "Medical Support", "Long Stay Rates"],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      cancellation: "Free cancellation until 24 hours before check-in",
      pets: false,
      smoking: false,
      children: true,
    },
    tags: ["featured", "medical-tourism", "long-stay"],
    featured: true,
  },
  {
    id: "lt-grg-apt-2bhk",
    slug: "lime-tree-2bhk-serviced-apartment-golf-course",
    name: "Lime Tree 2BHK Serviced Apartment, Golf Course Road",
    tagline: "Spacious. Furnished. Truly Home.",
    description:
      "A fully furnished 2BHK serviced apartment on Gurgaon's iconic Golf Course Road — designed for long stays, relocations, and project-based assignments. Features a full kitchen, separate living room, washer, and high-speed WiFi.",
    propertyType: "serviced-apartment",
    location: {
      city: "Gurgaon",
      state: "Haryana",
      address: "Golf Course Road, DLF Phase 4, Gurugram",
      area: "Golf Course Road",
      pincode: "122002",
      nearbyAttractions: ["Golf Course Road Offices", "Sector 42-43 Metro (8 min)", "DLF Cybercity (15 min)", "Galleria Market (5 min)"],
    },
    images: [
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-two-bhk-service-apartment-golf-course-road-gurgaon/10_-_Copy_fyq6iv",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-two-bhk-service-apartment-golf-course-road-gurgaon/LT-Manesar-6_nf9ile",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-two-bhk-service-apartment-golf-course-road-gurgaon/LT-Manesar-3_afgnmo",
    ],
    heroImage: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-two-bhk-service-apartment-golf-course-road-gurgaon/10_-_Copy_fyq6iv",
    rating: 4.7,
    reviewCount: 423,
    starCategory: 4,
    pricePerNight: 3499,
    originalPrice: 5000,
    rooms: [
      {
        id: "lt-grg-apt-2bhk-r",
        type: "2bhk",
        name: "2 BHK Apartment",
        description: "60 sqm apartment with two bedrooms, full kitchen, dining, and dedicated workspace.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-two-bhk-service-apartment-golf-course-road-gurgaon/10_-_Copy_fyq6iv"],
        size: 60,
        maxOccupancy: 4,
        bedType: "2x Double",
        pricePerNight: 3499,
        originalPrice: 5000,
        amenities: ["Full Kitchen", "Washing Machine", "Free WiFi", "AC", "Smart TV", "Work Desk", "Dining Table"],
        available: true,
        cancellationPolicy: "free",
        breakfastIncluded: false,
      },
    ],
    amenities: ["Full Kitchen", "Washing Machine", "Free WiFi", "AC", "Weekly Housekeeping", "Parking", "Power Backup", "24x7 Security", "Elevator"],
    highlights: ["Full Kitchen", "Washing Machine", "Weekly Housekeeping", "Monthly Discounts"],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      cancellation: "Free cancellation until 48 hours before check-in",
      pets: false,
      smoking: false,
      children: true,
    },
    tags: ["featured", "serviced-apartment", "long-stay"],
    featured: true,
  },
  {
    id: "lt-grg-apt-3bhk-dlf",
    slug: "lime-tree-3bhk-serviced-apartment-dlf-phase-5",
    name: "Lime Tree 3BHK Serviced Apartment, DLF Phase-5",
    tagline: "Premium Living in Gurgaon's Finest Address",
    description:
      "A luxuriously appointed 3BHK serviced apartment in the prestigious DLF Phase-5. Ideal for families, senior executives, and long-term project stays requiring maximum space and privacy.",
    propertyType: "serviced-apartment",
    location: {
      city: "Gurgaon",
      state: "Haryana",
      address: "DLF Phase-5, Sector 43, Gurugram",
      area: "DLF Phase-5",
      pincode: "122009",
      nearbyAttractions: ["DLF Cyber City (10 min)", "Huda City Centre Metro (5 min)", "Ambience Mall (7 min)", "Golf Course Road (8 min)"],
    },
    images: [
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-3bhk-serviced-apartments-dlf-phase---5-gurgaon/DSC01875_xqheud",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-3bhk-serviced-apartments-dlf-phase---5-gurgaon/DSC01865_xgn4sq",
    ],
    heroImage: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-3bhk-serviced-apartments-dlf-phase---5-gurgaon/DSC01875_xqheud",
    rating: 4.8,
    reviewCount: 201,
    starCategory: 4,
    pricePerNight: 5499,
    originalPrice: 8000,
    rooms: [
      {
        id: "lt-grg-apt-3bhk-dlf-r",
        type: "3bhk",
        name: "3 BHK Premium Apartment",
        description: "90 sqm premium apartment — three bedrooms, living room, full kitchen, and balcony.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-3bhk-serviced-apartments-dlf-phase---5-gurgaon/DSC01875_xqheud"],
        size: 90,
        maxOccupancy: 6,
        bedType: "3x Double",
        pricePerNight: 5499,
        originalPrice: 8000,
        amenities: ["Full Kitchen", "Washing Machine", "Free WiFi", "AC", "Smart TV", "Balcony", "Dining Table", "Work Desk"],
        available: true,
        cancellationPolicy: "free",
        breakfastIncluded: false,
      },
    ],
    amenities: ["Full Kitchen", "Washing Machine", "Free WiFi", "AC", "Weekly Housekeeping", "Covered Parking", "Power Backup", "24x7 Security", "Elevator", "Gym Access"],
    highlights: ["Premium DLF Phase-5", "3 Bedrooms", "Gym & Pool", "Family Friendly"],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      cancellation: "Free cancellation until 48 hours before check-in",
      pets: false,
      smoking: false,
      children: true,
    },
    tags: ["premium", "serviced-apartment", "family", "long-stay"],
    featured: false,
  },
  {
    id: "lt-del-gk2",
    slug: "lime-tree-greater-kailash-2-delhi",
    name: "Lime Tree, Greater Kailash-2",
    tagline: "South Delhi's Finest Boutique Stay",
    description:
      "A stylish boutique hotel in South Delhi's most sought-after residential colony. Greater Kailash-2 offers tree-lined streets, premium markets, and easy metro access — all just steps from your door.",
    propertyType: "hotel",
    location: {
      city: "Delhi",
      state: "Delhi",
      address: "E-564, Lala Lajpat Rai Rd, Block E, Greater Kailash II, New Delhi",
      area: "Greater Kailash-2",
      pincode: "110048",
      nearbyAttractions: ["M-Block Market GK2 (5 min)", "Nehru Place Metro (8 min)", "Hauz Khas Village (15 min)", "Lajpat Nagar (10 min)"],
    },
    images: [
      "https://assets.simplotel.com/simplotel/image/upload/x_195,y_0,w_1260,h_927,r_0,c_crop/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-boutique-bed-breakfast-|-nehru-place-metro-1753349469/Hotels-in-Delhi-Lime-Stay-Bedroom_sktjlo",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-boutique-bed-breakfast-|-nehru-place-metro-1753349469/Hotels-in-Delhi-Lime-Stay-Lobby_ykhkax",
    ],
    heroImage: "https://assets.simplotel.com/simplotel/image/upload/x_195,y_0,w_1260,h_927,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-boutique-bed-breakfast-|-nehru-place-metro-1753349469/Hotels-in-Delhi-Lime-Stay-Bedroom_sktjlo",
    rating: 4.4,
    reviewCount: 876,
    starCategory: 3,
    pricePerNight: 2299,
    originalPrice: 3200,
    rooms: [
      {
        id: "lt-del-gk2-std",
        type: "standard",
        name: "Standard Room",
        description: "Elegant room with South Delhi character and contemporary amenities.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09854_ihjj3s"],
        size: 25,
        maxOccupancy: 2,
        bedType: "Double",
        pricePerNight: 2299,
        originalPrice: 3200,
        amenities: ["Free WiFi", "AC", "TV", "Work Desk", "Geyser"],
        available: true,
        cancellationPolicy: "free",
        breakfastIncluded: true,
      },
    ],
    amenities: ["Free WiFi", "Complimentary Breakfast", "24x7 Front Desk", "Room Service", "Laundry", "Parking"],
    highlights: ["GK2 Prime Location", "Breakfast Included", "Metro Connectivity", "South Delhi Character"],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      cancellation: "Free cancellation until 24 hours before check-in",
      pets: false,
      smoking: false,
      children: true,
    },
    tags: ["featured", "boutique", "delhi"],
    featured: true,
  },
  {
    id: "lt-grnoida-expo",
    slug: "lime-tree-hotel-india-expo-mart",
    name: "Lime Tree Hotel Near India Expo Mart",
    tagline: "Your Exhibition Base in Greater Noida",
    description:
      "The ideal base for trade shows, exhibitions, and events at India Expo Mart. Close to the venue, well-connected by metro, and equipped with everything business travelers need.",
    propertyType: "hotel",
    location: {
      city: "Greater Noida",
      state: "Uttar Pradesh",
      address: "Near India Expo Mart, Knowledge Park 2, Greater Noida",
      area: "Knowledge Park 2",
      pincode: "201306",
      nearbyAttractions: ["India Expo Mart (5 min)", "Pari Chowk (8 min)", "Aqua Line Metro (10 min)", "Formula 1 Circuit (15 min)"],
    },
    images: [
      "https://assets.simplotel.com/simplotel/image/upload/x_194,y_0,w_3852,h_2832,r_0,c_crop/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-and-banquet-greater-noida/DSC00679_nf9ilw",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-and-banquet-greater-noida/DSC00710_ikntox",
    ],
    heroImage: "https://assets.simplotel.com/simplotel/image/upload/x_194,y_0,w_3852,h_2832,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-and-banquet-greater-noida/DSC00679_nf9ilw",
    rating: 4.2,
    reviewCount: 543,
    starCategory: 3,
    pricePerNight: 1499,
    originalPrice: 2200,
    rooms: [
      {
        id: "lt-grnoida-expo-std",
        type: "standard",
        name: "Standard Room",
        description: "Clean, comfortable room built for exhibition and business travelers.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09854_ihjj3s"],
        size: 20,
        maxOccupancy: 2,
        bedType: "Double",
        pricePerNight: 1499,
        originalPrice: 2200,
        amenities: ["Free WiFi", "AC", "TV", "Work Desk"],
        available: true,
        cancellationPolicy: "free",
        breakfastIncluded: true,
      },
    ],
    amenities: ["Free WiFi", "Complimentary Breakfast", "Parking", "Power Backup", "24x7 Front Desk", "Conference Room"],
    highlights: ["5 min from India Expo Mart", "Exhibition Season Rates", "Metro Access", "Conference Facilities"],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      cancellation: "Free cancellation until 24 hours before check-in",
      pets: false,
      smoking: false,
      children: true,
    },
    tags: ["business", "greater-noida", "expo"],
    featured: false,
  },
  {
    id: "lt-jai-banquet",
    slug: "lime-tree-hotel-banquet-jaipur",
    name: "Lime Tree Hotel & Banquet, Jaipur",
    tagline: "Pink City Stays & Grand Celebrations",
    description:
      "Lime Tree's Jaipur property blends Rajasthani hospitality with modern comforts. The hotel features a banquet hall for weddings and events, making it the ideal choice for celebrations in the Pink City.",
    propertyType: "hotel",
    location: {
      city: "Jaipur",
      state: "Rajasthan",
      address: "Jaipur City Centre, Rajasthan",
      area: "City Centre",
      pincode: "302001",
      nearbyAttractions: ["Hawa Mahal (15 min)", "City Palace (20 min)", "Amer Fort (30 min)", "Jaipur Junction Railway Station (10 min)"],
    },
    images: [
      "https://assets.simplotel.com/simplotel/image/upload/x_0,y_11,w_1448,h_1064,r_0,c_crop/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-banquet-jaipur/hotel-lobby",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-banquet-jaipur/Banquet_gkxjry",
    ],
    heroImage: "https://assets.simplotel.com/simplotel/image/upload/x_0,y_11,w_1448,h_1064,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-banquet-jaipur/hotel-lobby",
    rating: 4.3,
    reviewCount: 712,
    starCategory: 3,
    pricePerNight: 2199,
    originalPrice: 3200,
    rooms: [
      {
        id: "lt-jai-std",
        type: "standard",
        name: "Standard Room",
        description: "Comfortable room with Rajasthani touches and all modern amenities.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09854_ihjj3s"],
        size: 22,
        maxOccupancy: 2,
        bedType: "Double",
        pricePerNight: 2199,
        originalPrice: 3200,
        amenities: ["Free WiFi", "AC", "TV", "Geyser", "Work Desk"],
        available: true,
        cancellationPolicy: "free",
        breakfastIncluded: true,
      },
    ],
    amenities: ["Free WiFi", "Banquet Hall", "Complimentary Breakfast", "Parking", "Power Backup", "24x7 Front Desk", "Wedding Planning Assistance"],
    highlights: ["Heritage City Location", "Banquet for Events", "Breakfast Included", "Sightseeing Assistance"],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      cancellation: "Free cancellation until 24 hours before check-in",
      pets: false,
      smoking: false,
      children: true,
    },
    tags: ["featured", "banquet", "jaipur", "tourism"],
    featured: true,
  },
  {
    id: "lt-goa-villa",
    slug: "lime-tree-4bhk-villa-goa",
    name: "Lime Tree 4BHK Villa with Private Pool, Goa",
    tagline: "Your Private Paradise on the Goan Coast",
    description:
      "A stunning 4BHK luxury villa with a private swimming pool in Goa — the ultimate retreat for families and groups. Fully staffed, beautifully furnished, and set amidst lush tropical gardens.",
    propertyType: "villa",
    location: {
      city: "Goa",
      state: "Goa",
      address: "North Goa, Goa",
      area: "North Goa",
      pincode: "403001",
      nearbyAttractions: ["Private Beach (10 min)", "Calangute Beach (15 min)", "Panjim City (20 min)", "Goa Airport (35 min)"],
    },
    images: [
      "https://assets.simplotel.com/simplotel/image/upload/x_67,y_0,w_1306,h_960,r_0,c_crop/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-villa-with-private-pool-|-luxury-stay-in-goa/Pool2_7939cbbc",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-villa-with-private-pool-|-luxury-stay-in-goa/Villa_living_room_klxmue",
      "https://assets.simplotel.com/simplotel/image/upload/q_80,w_1200,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-villa-with-private-pool-|-luxury-stay-in-goa/Bedroom_Master_uqzopw",
    ],
    heroImage: "https://assets.simplotel.com/simplotel/image/upload/x_67,y_0,w_1306,h_960,r_0,c_crop/q_80,w_1600,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-villa-with-private-pool-|-luxury-stay-in-goa/Pool2_7939cbbc",
    rating: 4.9,
    reviewCount: 89,
    starCategory: 5,
    pricePerNight: 18000,
    originalPrice: 25000,
    rooms: [
      {
        id: "lt-goa-villa-r",
        type: "3bhk",
        name: "4BHK Villa (Entire Villa)",
        description: "Four luxurious bedrooms, private pool, chef on request, and tropical garden.",
        images: ["https://assets.simplotel.com/simplotel/image/upload/x_67,y_0,w_1306,h_960,r_0,c_crop/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-villa-with-private-pool-|-luxury-stay-in-goa/Pool2_7939cbbc"],
        size: 350,
        maxOccupancy: 10,
        bedType: "4x King",
        pricePerNight: 18000,
        originalPrice: 25000,
        amenities: ["Private Pool", "Full Kitchen", "AC", "Smart TV", "Washer", "BBQ Area", "Garden", "Chef on Request"],
        available: true,
        cancellationPolicy: "partial",
        breakfastIncluded: false,
      },
    ],
    amenities: ["Private Pool", "Full Staff", "Full Kitchen", "AC in all rooms", "Smart TVs", "BBQ Area", "Garden", "Parking", "Chef on Request"],
    highlights: ["Private Pool", "4 Bedrooms", "10 Guests", "Full Staff Included"],
    policies: {
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      cancellation: "50% refund for cancellations 7+ days before check-in",
      pets: false,
      smoking: false,
      children: true,
    },
    tags: ["featured", "villa", "luxury", "goa", "pool"],
    featured: true,
  },
];

export const GLOBAL_REVIEWS: Review[] = [
  {
    id: "rev-001",
    guestName: "Rahul Mehta",
    rating: 5,
    title: "Best stay near Medanta — highly recommended",
    comment:
      "My mother was undergoing treatment at Medanta and we stayed at Lime Tree nearby for 3 weeks. The staff was incredibly understanding, always available, and the room was spotless. They even helped arrange pharmacy runs and cab bookings. Exceptional care during a difficult time.",
    date: "2026-06-10",
    stayType: "long",
    verified: true,
    helpful: 87,
    platform: "google",
  },
  {
    id: "rev-002",
    guestName: "Anjali Singh",
    rating: 5,
    title: "Perfect corporate stay in Gurgaon",
    comment:
      "I've been staying at Lime Tree IFFCO Chowk every month for my Gurgaon visits. Location is unbeatable — 2 minutes from the metro and 10 minutes to Cyber Hub. The breakfast is excellent, rooms are well-maintained, and the check-in is always smooth. My top pick in Gurgaon.",
    date: "2026-05-22",
    stayType: "corporate",
    verified: true,
    helpful: 64,
    platform: "google",
  },
  {
    id: "rev-003",
    guestName: "Vikram Nair",
    rating: 4,
    title: "Great serviced apartment for long project stay",
    comment:
      "Spent 6 weeks at the Golf Course Road 2BHK apartment. The fully furnished kitchen made such a difference — I could cook my own meals and feel at home. Fast WiFi, weekly housekeeping, and the price for a 1-month stay was very competitive. Would definitely book again.",
    date: "2026-06-01",
    stayType: "long",
    verified: true,
    helpful: 52,
    platform: "google",
  },
  {
    id: "rev-004",
    guestName: "Priya Sharma",
    rating: 5,
    title: "Wonderful wedding venue in Jaipur",
    comment:
      "We hosted our wedding at Lime Tree Jaipur and it was magical. The banquet team was incredibly professional, the food was superb, and the décor exceeded our expectations. Our guests from Delhi and Mumbai were all impressed. Thank you Lime Tree team!",
    date: "2026-05-15",
    stayType: "short",
    verified: true,
    helpful: 43,
    platform: "google",
  },
  {
    id: "rev-005",
    guestName: "Deepak Agarwal",
    rating: 5,
    title: "Lime Tree GK2 — best value in South Delhi",
    comment:
      "Consistently excellent stays at the Greater Kailash-2 property. South Delhi location is perfect for accessing clients across the city. The team remembers regular guests and it really feels personal. Breakfast quality is above what you'd expect at this price.",
    date: "2026-06-18",
    stayType: "corporate",
    verified: true,
    helpful: 39,
    platform: "google",
  },
  {
    id: "rev-006",
    guestName: "Meera Krishnamurthy",
    rating: 5,
    title: "Amazing Goa villa — our best holiday ever",
    comment:
      "The Goa 4BHK villa was absolutely stunning. Private pool, lush garden, and fully staffed — it was luxury at a very reasonable price for a group of 8. The Lime Tree team arranged a chef for us on request. We've already booked again for next year!",
    date: "2026-04-28",
    stayType: "short",
    verified: true,
    helpful: 71,
    platform: "google",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-001",
    slug: "service-apartments-gurgaon-best-for-temporary-stay",
    title: "Why Service Apartments Are Best for Temporary Stay in Gurgaon?",
    excerpt:
      "Service apartments in Gurgaon offer the perfect balance of home comforts and hotel conveniences — here's why thousands of corporate travelers choose them over hotels.",
    content: "",
    image: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-two-bhk-service-apartment-golf-course-road-gurgaon/10_-_Copy_fyq6iv",
    author: "Lime Tree Team",
    category: "Serviced Apartments",
    tags: ["Gurgaon", "Serviced Apartments", "Corporate Travel"],
    publishedAt: "2026-06-15",
    readTime: 7,
    featured: true,
  },
  {
    id: "blog-002",
    slug: "visiting-gurgaon-for-business-stay-service-apartments",
    title: "Visiting Gurgaon for Business? Why You Should Stay in a Service Apartment",
    excerpt:
      "From Cyber City to Golf Course Road — if you're in Gurgaon for work, a service apartment beats a hotel room every single time. Here's the complete guide.",
    content: "",
    image: "https://assets.simplotel.com/simplotel/image/upload/w_5000,h_3333/x_234,y_0,w_4532,h_3333,r_0,c_crop/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09899_ozpuez",
    author: "Lime Tree Team",
    category: "Business Travel",
    tags: ["Business Travel", "Gurgaon", "Tips"],
    publishedAt: "2026-05-28",
    readTime: 6,
    featured: true,
  },
  {
    id: "blog-003",
    slug: "hotel-near-medanta-gurgaon-comfortable-stay",
    title: "Hotel Near Medanta Gurgaon – Comfortable Stay at Lime Tree Hotel",
    excerpt:
      "If you or a loved one is seeking treatment at Medanta–The Medicity, Lime Tree's nearby hotels offer comfort, accessibility, and compassionate support.",
    content: "",
    image: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-service-apartment-private-limited/LT-Sector_38-115_4e3d5eaa",
    author: "Lime Tree Team",
    category: "Medical Tourism",
    tags: ["Medical Tourism", "Medanta", "Gurgaon"],
    publishedAt: "2026-05-10",
    readTime: 5,
    featured: false,
  },
  {
    id: "blog-004",
    slug: "types-of-living-arrangements-gurgaon",
    title: "Types of Living Arrangements You'll Find in Gurgaon",
    excerpt:
      "From PG accommodations to luxury serviced apartments — understanding your options in Gurgaon can save you money and ensure a comfortable stay.",
    content: "",
    image: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-near-32nd-avenue-sector-15-gurgaon/Lime_Tree_Hotels_32nd_Avenue_91_bouivm",
    author: "Lime Tree Team",
    category: "Destination Guide",
    tags: ["Gurgaon", "Living", "Guide"],
    publishedAt: "2026-04-20",
    readTime: 8,
    featured: false,
  },
];

export const OFFERS: Offer[] = [
  {
    id: "offer-001",
    title: "Early Bird Discount",
    description: "Book 30+ days in advance and save big. The earlier you plan, the more you save — locked-in rates with free cancellation.",
    image: "https://assets.simplotel.com/simplotel/image/upload/w_5000,h_3333/x_234,y_0,w_4532,h_3333,r_0,c_crop/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-sushant-lok-gurgaon---next-to-iffco-chowk-metro-station/DSC09899_ozpuez",
    discount: 20,
    discountType: "percentage",
    code: "EARLYBIRD20",
    validFrom: "2026-07-01",
    validTo: "2026-12-31",
    terms: ["Must book 30 days in advance", "Free cancellation until 7 days before check-in", "Valid on direct bookings only"],
    applicable: ["All Hotels", "Serviced Apartments"],
    featured: true,
  },
  {
    id: "offer-002",
    title: "Weekly Discount",
    description: "Stay 7 nights and get a significant discount. Perfect for project assignments, medical stays, and extended business trips.",
    image: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-3bhk-serviced-apartments-dlf-phase---5-gurgaon/DSC01875_xqheud",
    discount: 15,
    discountType: "percentage",
    code: "WEEKLY15",
    validFrom: "2026-07-01",
    validTo: "2026-12-31",
    terms: ["Minimum 7 nights stay", "Valid for hotels and apartments", "Cannot be combined with other offers"],
    applicable: ["Hotels", "Serviced Apartments"],
    featured: true,
  },
  {
    id: "offer-003",
    title: "Monthly Stay Package",
    description: "Month-long stays at unbeatable rates — with complimentary laundry, dedicated account manager, and a 30% discount.",
    image: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-two-bhk-service-apartment-golf-course-road-gurgaon/10_-_Copy_fyq6iv",
    discount: 30,
    discountType: "percentage",
    code: "MONTHLY30",
    validFrom: "2026-07-01",
    validTo: "2026-12-31",
    terms: ["Minimum 30 nights stay", "Complimentary laundry included", "Dedicated Relationship Manager assigned"],
    applicable: ["Serviced Apartments"],
    featured: true,
  },
  {
    id: "offer-004",
    title: "Last Minute Deal",
    description: "Plans changed? Book within 48 hours of check-in and save up to 10%. Great rates, instant confirmation.",
    image: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-near-32nd-avenue-sector-15-gurgaon/Lime_Tree_Hotels_32nd_Avenue_91_bouivm",
    discount: 10,
    discountType: "percentage",
    code: "LASTMIN10",
    validFrom: "2026-07-01",
    validTo: "2026-12-31",
    terms: ["Must book within 48 hours of check-in", "Non-refundable booking", "Subject to availability"],
    applicable: ["All Hotels"],
    featured: false,
  },
  {
    id: "offer-005",
    title: "Healing Stay Package",
    description: "Designed for medical travelers visiting Medanta, Artemis, or other top hospitals. Includes pick-up/drop, pharmacy assistance, and priority support.",
    image: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-service-apartment-private-limited/LT-Sector_38-115_4e3d5eaa",
    discount: 15,
    discountType: "percentage",
    code: "HEALING15",
    validFrom: "2026-07-01",
    validTo: "2026-12-31",
    terms: ["Valid for medical tourism bookings", "Must mention at time of booking", "Pick-up/drop subject to availability"],
    applicable: ["Near-Hospital Properties"],
    featured: true,
  },
  {
    id: "offer-006",
    title: "Corporate Flexi Rate",
    description: "Exclusive corporate rates with free cancellation up to 6 hours before check-in, GST invoicing, and 20% F&B discount.",
    image: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-and-banquet-hall-near-huda-metro-gurgaon/Lime_Tree_Hotel_Huda_City_Center_Gurgaon_10_xj2mge",
    discount: 20,
    discountType: "percentage",
    code: "CORPFLEX",
    validFrom: "2026-07-01",
    validTo: "2026-12-31",
    terms: ["Valid for registered corporate accounts", "GST invoice provided", "20% F&B discount on all orders"],
    applicable: ["All Properties"],
    featured: false,
  },
];

export const HOLIDAY_PACKAGES = [
  {
    id: "pkg-manali",
    title: "Manali Escape",
    duration: "4 Days / 3 Nights",
    image: "https://assets.simplotel.com/simplotel/image/upload/x_196,y_0,w_3808,h_2800,r_0,c_crop/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-banquet-vrindavan/Vrindavan-59_564e1a7a",
    highlights: ["Rohtang Pass", "Solang Valley", "Kullu", "Manikaran"],
    description: "An exhilarating 4-day journey through Manali — cultural landmarks, adventure thrills at Solang Valley, and the breathtaking Rohtang Pass.",
    startingPrice: 12999,
    slug: "manali-escape",
  },
  {
    id: "pkg-rishikesh",
    title: "Rishikesh Serenity",
    duration: "3 Nights / 4 Days",
    image: "https://assets.simplotel.com/simplotel/image/upload/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotels-service-apartment-private-limited/Vrindavan-58_1c299844",
    highlights: ["Haridwar", "Ganga Aarti", "River Rafting", "Trekking"],
    description: "Experience Haridwar and Rishikesh — sacred temples, the mesmerizing Ganga Aarti, river rafting, and trekking to hidden waterfalls.",
    startingPrice: 9999,
    slug: "rishikesh-serenity",
  },
  {
    id: "pkg-golden-triangle",
    title: "Golden Triangle",
    duration: "6 Nights / 7 Days",
    image: "https://assets.simplotel.com/simplotel/image/upload/x_0,y_11,w_1448,h_1064,r_0,c_crop/q_80,w_800,dpr_1,f_auto,fl_progressive,c_limit/lime-tree-hotel-banquet-jaipur/hotel-lobby",
    highlights: ["Delhi", "Taj Mahal, Agra", "Jaipur", "Heritage Sites"],
    description: "India's iconic Golden Triangle — the grandeur of Delhi, the timeless Taj Mahal in Agra, and the royal splendour of Jaipur.",
    startingPrice: 24999,
    slug: "golden-triangle",
  },
];

export const TRUST_STATS = [
  { value: 12, suffix: "+", label: "Years of Trust", sublabel: "Est. 2011", icon: "calendar" },
  { value: 500, suffix: "+", label: "Rooms", sublabel: "Across properties", icon: "bed" },
  { value: 30, suffix: "+", label: "Properties", sublabel: "7 cities", icon: "building" },
  { value: 4.4, suffix: "★", label: "Avg Rating", sublabel: "Verified guests", icon: "star", decimals: 1 },
  { value: 50000, suffix: "+", label: "Happy Guests", sublabel: "Since 2013", icon: "users" },
];

export const CORPORATE_BENEFITS = [
  { title: "Dedicated Relationship Manager", desc: "Every corporate account gets a personal RM for seamless bookings and escalations." },
  { title: "GST-Compliant Invoicing", desc: "Transparent, auto-generated GST invoices for every stay — expense management made easy." },
  { title: "Bill to Company", desc: "Direct billing to your organization. No employee reimbursement hassle." },
  { title: "Self-Booking Portal", desc: "Manage reservations, download invoices, and track usage — all in one dashboard." },
  { title: "20% F&B Discount", desc: "Flat 20% off on all food and beverage orders for corporate guests." },
  { title: "Flexible Cancellation", desc: "Cancel up to 6 hours before check-in — built for dynamic travel schedules." },
  { title: "Early Check-In", desc: "Priority early check-in for early morning arrivals, subject to availability." },
  { title: "Airport Transfers", desc: "Professional airport pick-up and drop service for corporate accounts." },
];

export const AMENITY_ICONS: Record<string, string> = {
  "Free WiFi": "wifi",
  "Swimming Pool": "waves",
  "Gym": "dumbbell",
  "Spa": "sparkles",
  "Restaurant": "utensils",
  "Bar": "wine",
  "Business Center": "briefcase",
  "Parking": "car",
  "Airport Shuttle": "plane",
  "Concierge": "bell",
  "Room Service": "bell",
  "Laundry": "shirt",
  "Power Backup": "zap",
  "24x7 Security": "shield",
  "Kitchen": "chef-hat",
  "Smart TV": "tv",
  "Minibar": "glass-water",
};
